### ISSUE TITLE
can't consume from gstreamer (astits: only one sync byte detected in first 193 bytes error)

### ISSUE THREAD

**Issue by steely-glint** [flavioribeiro/donut#23]
Hi, I've been experimenting with this package with the aim of adding a WHIP mode.
But I can't get the demo to interop with gstreamer.

I added some debug and I see an error is returned :
`astits: only one sync byte detected in first 193 bytes`
and then it stops consuming - I see no video on the webRTC browser
(fork is here [https://github.com/everycastlabs/donut](https://github.com/everycastlabs/donut))

I tried the same code against OBS and it works (although it is very jerky)

My pipeline looks like this:

`exec gst-launch-1.0 -v \
	v4l2src device=/dev/video50 \
	! video/x-raw,width=1920,height=1080,framerate=30/1,format=NV12\
	! videoconvert \
	! video/x-raw,width=1920,height=1080,framerate=30/1,format=RGB\
	! amlvenc  encoder-buffer-size=1024 min-buffers=6 max-buffers=6 gop=1 bitrate=10000 framerate=30 ! video/x-h264,profile=high \
! mpegtsmux ! srtserversink streamid=test uri=srt://:8888/`

Any hints as to where I should look ?

**Comment by flavioribeiro** [comment]
hey @steely-glint! sorry just seeing this now. Were you able to make this work?

**Comment by Sean-Der** [comment]
A fork exists that added WHIP support! https://github.com/everycastlabs/donut/

Maybe can pulled into mainline? I haven't looked at deeply, but I always had hoped that `donut` would become the ultimate protocol bridger service thingy :)

**Comment by steely-glint** [comment]
It has been a while, but that fork worked ok when I last looked at it. 
Happy to help with a merge if that is thought appropriate.
