### ISSUE TITLE
Install fails due to undefined references

### ISSUE THREAD

**Issue by samisb** [flavioribeiro/donut#7]
[ec2-user@ip-172-31-35-83 donut]$ go build
# github.com/asticode/go-astisrt/pkg
/tmp/go-build1794952141/b135/_cgo_main.o:/tmp/go-build/cgo-generated-wrappers:5: undefined reference to `SRT_INVALID_SOCK'
/tmp/go-build1794952141/b135/_cgo_main.o:/tmp/go-build/cgo-generated-wrappers:2: undefined reference to `SRT_ERROR'
collect2: error: ld returned 1 exit status

**Comment by flavioribeiro** [comment]
should be fixed by https://github.com/flavioribeiro/donut/pull/12
